---
INIT_HP:
    ALGO: LLMPPO
    BATCH_SIZE: 32
    BETA: 0.05
    CLIP_COEF: 0.2
    GAE_LAMBDA: 0.95
    GAMMA: 1.0
    LR_ACTOR: 0.0001
    LR_CRITIC: 0.0001
    MAX_GRAD_NORM: 1.0
    TEMPERATURE: 0.4
    UPDATE_EPOCHS: 4
    VF_COEF: 0.1

DEBUG:
    test_policy_only: false
    policy_only_vf_coef: 0.0
    eval_episodes: 128
    max_context_length: 128
    max_output_tokens: 1
    max_sample_steps: 12288
    evaluation_interval: 50
    seeds: [0]
    lora:
        r: 8
        lora_alpha: 32
        target_modules: [c_attn, c_proj, c_fc]
