---
algorithm:
    name: NeuralUCB
    batch_size: 64
    lr: 0.001
    learn_step: 2
    gamma: 1.0
    lamb: 1.0
    reg: 0.000625

environment:
    name: IRIS
    features: tests/data/iris_features.csv
    targets: tests/data/iris_targets.csv
mutation:
    probabilities:
        no_mut: 0.4
        arch_mut: 0.2
        new_layer: 0.2
        params_mut: 0.2
        act_mut: 0.2
        rl_hp_mut: 0.2
    rl_hp_selection:
        lr:
            min: 0.0000625
            max: 0.01
        batch_size:
            min: 8
            max: 512
        learn_step:
            min: 1
            max: 10
    mutation_sd: 0.1
    rand_seed: 42

network:
    latent_dim: 128
    arch: mlp

    encoder_config:
        hidden_size:
            - 128

    head_config:
        hidden_size:
            - 128

replay_buffer:
    max_size: 10_000

tournament_selection:
    tournament_size: 2
    elitism: true

training:
    max_steps: 10_000
    target_score: 96.0
    pop_size: 4
    evo_steps: 500
    eval_steps: 500
    eval_loop: 1
