---
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
fsdp_config: {}
machine_rank: 0
main_process_ip:
main_process_port:
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
use_cpu: false
