from pathlib import Path

# Vendored tiny LLM (Qwen2 architecture) for offline testing.
# Generated by tests/assets/build_tiny_llm_fixture.py.
TINY_LLM_FIXTURE_PATH = str(Path(__file__).parent / "assets" / "tiny_llm")
