---
algorithm:
    name: PPO
    batch_size: 128
    lr: 0.001
    learn_step: 2048
    gamma: 0.99
    gae_lambda: 0.95
    action_std_init: 0.6
    clip_coef: 0.2
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.5
    target_kl:
    update_epochs: 4
    share_encoders: true

environment:
    name: LunarLander-v3
    num_envs: 16
mutation:
    probabilities:
        no_mut: 0.4
        arch_mut: 0.2
        new_layer: 0.2
        params_mut: 0.2
        act_mut: 0.0
        rl_hp_mut: 0.2
    rl_hp_selection:
        lr:
            min: 0.0001
            max: 0.01
        batch_size:
            min: 8
            max: 1024
        learn_step:
            min: 256
            max: 8192
        ent_coef:
            min: 0.001
            max: 0.1
        update_epochs:
            min: 1
            max: 10
    mutation_sd: 0.1
    rand_seed: 42

network:
    latent_dim: 64
    arch: mlp
    encoder_config:
        hidden_size:
            - 64
        activation: ReLU
        min_mlp_nodes: 64
        max_mlp_nodes: 500
        layer_norm: true

    head_config:
        hidden_size:
            - 64
        activation: ReLU
        min_hidden_layers: 1
        max_hidden_layers: 3
        min_mlp_nodes: 64
        max_mlp_nodes: 500
        output_vanish: true
        layer_norm: true

tournament_selection:
    tournament_size: 2
    elitism: true

training:
    max_steps: 6_000_000
    target_score: 250.0
    pop_size: 4
    evo_steps: 10_240
    eval_steps:
    eval_loop: 1
