---
algorithm:
    name: PPO
    batch_size: 64
    lr: 0.0003
    learn_step: 16384
    gamma: 0.99
    gae_lambda: 0.95
    action_std_init: 0.6
    clip_coef: 0.2
    ent_coef: 0.0001
    vf_coef: 0.5
    max_grad_norm: 0.5
    target_kl:
    update_epochs: 4
    share_encoders: true
    recurrent: true

environment:
    name: CartPole-v1
    num_envs: 16
mutation:
    probabilities:
        no_mut: 0.4
        arch_mut: 0.0
        new_layer: 0.0
        params_mut: 0.2
        act_mut: 0.0
        rl_hp_mut: 0.2
    rl_hp_selection:
        lr:
            min: 0.0001
            max: 0.01
        batch_size:
            min: 8
            max: 1024
        learn_step:
            min: 256
            max: 8192
        ent_coef:
            min: 0.0001
            max: 0.001
    mutation_sd: 0.1
    rand_seed: 42

network:
    latent_dim: 64
    arch: lstm
    encoder_config:
        hidden_state_size: 64         # LSTM hidden state size
        num_layers: 1                 # Number of recurrent layers

    head_config:
        hidden_size:
            - 128
        activation: ReLU
        min_hidden_layers: 1
        max_hidden_layers: 2
        min_mlp_nodes: 128
        max_mlp_nodes: 500

tournament_selection:
    tournament_size: 2
    elitism: true

training:
    max_steps: 6_000_000
    target_score: 500.0
    pop_size: 2
    evo_steps: 16384
    eval_steps:
    eval_loop: 1
