[project]
name = "agilerl-arena"
version = "0.1.0"
description = "Arena Platform Client Library and CLI."
authors = [{ name = "Nick Ustaran-Anderegg", email = "dev@agilerl.com" }]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "click>=8.3.0",
    "lazy-loader>=0.4",
    "httpx>=0.27,<1",
    "numpy>=2.0.0,<3.0",
    "packaging>=20.0",
    "pydantic>=2.0,<3",
    "python-keycloak>=4.0,<6",
    "pyyaml>=6.0",
    "rich>=13.0,<14",
]

[project.scripts]
arena = "agilerl.arena.cli:main"

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["agilerl.arena*"]
namespaces = true
