---
algorithm:
    name: RainbowDQN
    batch_size: 64
    lr: 0.0001
    learn_step: 1
    gamma: 0.99
    tau: 0.001
    beta: 0.4
    prior_eps: 0.000001
    noise_std: 0.5
    num_atoms: 51
    v_min: -200.0
    v_max: 200.0
    n_step: 4

environment:
    name: LunarLander-v3
    num_envs: 16
mutation:
    probabilities:
        no_mut: 0.4
        arch_mut: 0.2
        new_layer: 0.2
        params_mut: 0.2
        act_mut: 0.2
        rl_hp_mut: 0.2
    rl_hp_selection:
        lr:
            min: 0.0000625
            max: 0.001
        batch_size:
            min: 8
            max: 512
        learn_step:
            min: 1
            max: 10
    mutation_sd: 0.1
    rand_seed: 42

network:
    latent_dim: 64
    arch: mlp

    encoder_config:
        hidden_size:
            - 128
        activation: ReLU
        min_mlp_nodes: 64
        max_mlp_nodes: 500

    head_config:
        hidden_size:
            - 128
        activation: ReLU
        min_hidden_layers: 1
        max_hidden_layers: 3
        min_mlp_nodes: 64
        max_mlp_nodes: 500

replay_buffer:
    max_size: 100_000

tournament_selection:
    tournament_size: 2
    elitism: true

training:
    max_steps: 1_000_000
    target_score: 470.0
    pop_size: 1
    evo_steps: 10_000
    eval_steps:
    eval_loop: 1
    learning_delay: 1000
