---
# PPO on EnvPool MuJoCo Playground PandaRobotiqPushCube-v1
#
# Observation: 48-dim flat vector  |  Action: 7-dim continuous Box(-1, 1)
# Episode length: 3000 steps

algorithm:
    name: PPO
    batch_size: 1600
    lr: 0.0006
    learn_step: 51200
    gamma: 0.994
    gae_lambda: 0.95
    action_std_init: 1.0
    clip_coef: 0.3
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.5
    target_kl:
    update_epochs: 8
    share_encoders: false

environment:
    name: PandaRobotiqPushCube-v1
    num_envs: 256

mutation:
    probabilities:
        no_mut: 1.0
        arch_mut: 0.0
        new_layer: 0.0
        params_mut: 0.0
        act_mut: 0.0
        rl_hp_mut: 0.0
    mutation_sd: 0.1
    rand_seed: 42

network:
    latent_dim: 64
    max_latent_dim: 64
    arch: mlp
    encoder_config:
        hidden_size:
            - 64
            - 64
            - 64
            - 64
        activation: GELU
        min_mlp_nodes: 64
        max_mlp_nodes: 256
        layer_norm: false
    head_config:
        hidden_size:
            - 64
            - 64
            - 64
            - 64
        activation: GELU
        min_hidden_layers: 1
        max_hidden_layers: 4
        min_mlp_nodes: 64
        max_mlp_nodes: 256
        output_vanish: true
        layer_norm: false

tournament_selection:
    tournament_size: 2
    elitism: true

training:
    max_steps: 2_000_000_000
    target_score:
    pop_size: 1
    evo_steps: 1638400
    eval_steps: 3000
    eval_loop: 1
