---
defaults:
    - policy@expert_policy: optimal_policy
    - policy@suboptimal_policy: wrong_policy
    - vocab: wordle_official

vocab:
    cache_path: data/wordle/vocab_cache_wordle_official.pkl
    fill_cache: true

expert_policy:
    cache_path: data/wordle/optimal_policy_cache_wordle_official.pkl
    progress_bar: false
    start_word_policy:
        start_words:

suboptimal_policy:
    vocab:
        name: vocab
        vocab_path: word_lists/wordle_official_guess.txt
        cache_path:
        fill_cache: true

n_trajectories: 20000
reward_every: 128
load_data:
save_path: data/wordle/expert_wordle_branch_100k.pkl
vocab_cache_save_path: data/wordle/vocab_cache_wordle_official.pkl
expert_policy_cache_save_path: data/wordle/optimal_policy_cache_wordle_official.pkl
suboptimal_policy_cache_save_path:
n_suboptimal: 1
