---
# Define initial hyperparameters
INIT_HP:
    ENV_NAME: CartPole-v1   # Gym environment name
    DATASET: /projects/2023/evo_wrappers/AgileRL/data/cartpole/cartpole_v1.1.0.h5 # Offline RL dataset
    ALGO: CQN                                         # Algorithm
    DOUBLE: true
  # Swap image channels dimension from last to first [H, W, C] -> [C, H, W]
    CHANNELS_LAST: false
    BATCH_SIZE: 256           # Batch size
    LR: 0.001                   # Learning rate
    EPISODES: 1000             # Max no. episodes
    TARGET_SCORE: 200.          # Early training stop at avg score of last 100 episodes
    GAMMA: 0.99                # Discount factor
    MEMORY_SIZE: 100000        # Max memory buffer size
    POLICY_FREQ: 2             # Policy update frequency
    LEARN_STEP: 1              # Learning frequency
    TAU: 0.001                  # For soft update of target parameters
    TOURN_SIZE: 2              # Tournament size
    ELITISM: true              # Elitism in tournament selection
    POP_SIZE: 6                # Population size
    EVO_EPOCHS: 20             # Evolution frequency
    WANDB: false               # Log with Weights and Biases

MUTATION_PARAMS:
    NO_MUT: 0.4                            # No mutation
    ARCH_MUT: 0.2                          # Architecture mutation
    NEW_LAYER: 0.2                         # New layer mutation
    PARAMS_MUT: 0                        # Network parameters mutation
    ACT_MUT: 0.2                             # Activation layer mutation
    RL_HP_MUT: 0.2                         # Learning HP mutation
  # Learning HPs to choose from
    RL_HP_SELECTION: [lr, batch_size]
    MUT_SD: 0.1                            # Mutation strength
    RAND_SEED: 42                          # Random seed
    MIN_LR: 0.0001                         # Define max and min limits for mutating RL hyperparams
    MAX_LR: 0.01
    MIN_BATCH_SIZE: 8
    MAX_BATCH_SIZE: 1024


NET_CONFIG: {arch: mlp, hidden_size: [64, 64]}
