---
algorithm:
    name: DPO
    batch_size: 16
    beta: 0.001
    update_epochs: 1
    max_grad_norm: 0.1
    reduce_memory_peak: false
    calc_position_embeddings: true
    use_separate_reference_adapter: true

mutation:
    mutation_sd: 0.1
    rand_seed: 42
    probabilities:
        no_mut: 0.1
        arch_mut: 0.0
        new_layer: 0.0
        params_mut: 0.0
        act_mut: 0.0
        rl_hp_mut: 0.6
    rl_hp_selection:
        lr:
            min: 0.0000001
            max: 0.00001
        beta:
            min: 0.0001
            max: 0.01

tournament_selection:
    tournament_size: 2
    elitism: true

training:
    pop_size: 4
    max_steps: 100_000
    evo_steps: 20
    eval_loop: 1
