---
# Define initial hyperparameters
INIT_HP:
    ENV_NAME: LunarLander-v2   # Gym environment name
    ALGO: Rainbow DQN           # Algorithm
  # Swap image channels dimension from last to first [H, W, C] -> [C, H, W]
    CHANNELS_LAST: false
    NUM_ENVS: 16               # Number of parallel environments for training
    BATCH_SIZE: 256           # Batch size
    LR: 0.001                   # Learning rate
    EPISODES: 1000             # Max no. episodes
    TARGET_SCORE: 200.          # Early training stop at avg score of last 100 episodes
    GAMMA: 0.99                # Discount factor
    MEMORY_SIZE: 100000        # Max memory buffer size
    POLICY_FREQ: 2             # Policy update frequency
    LEARN_STEP: 1              # Learning frequency
    N_STEP: 1                  # Step number to calculate td error
    PER: false                 # Use prioritized experience replay buffer
    ALPHA: 0.6                 # Prioritized replay buffer parameter
    BETA: 0.4                  # Importance sampling coefficient
    TAU: 0.001                  # For soft update of target parameters
    PRIOR_EPS: 0.000001         # Minimum priority for sampling
    NUM_ATOMS: 51               # Unit number of support
    V_MIN: 0.                   # Minimum value of support
    V_MAX: 200.                 # Maximum value of support
    TOURN_SIZE: 2              # Tournament size
    ELITISM: true              # Elitism in tournament selection
    POP_SIZE: 6                # Population size
    EVO_LOOP: 3                # Number of evaluation episodes
    EVO_EPOCHS: 20             # Evolution frequency
    WANDB: true               # Log with Weights and Biases

MUTATION_PARAMS:
    NO_MUT: 0.1                            # No mutation
    ARCH_MUT: 0.2                          # Architecture mutation
    NEW_LAYER: 0.5                         # New layer mutation
    PARAMS_MUT: 0.2                        # Network parameters mutation
    ACT_MUT: 0                             # Activation layer mutation
    RL_HP_MUT: 0.2                         # Learning HP mutation
  # Learning HPs to choose from
    RL_HP_SELECTION: [lr, batch_size]
    MUT_SD: 0.1                            # Mutation strength
    RAND_SEED: 42                          # Random seed
    MIN_LR: 0.0001                         # Define max and min limits for mutating RL hyperparams
    MAX_LR: 0.01
    MIN_LEARN_STEP: 1
    MAX_LEARN_STEP: 200
    MIN_BATCH_SIZE: 8
    MAX_BATCH_SIZE: 1024


NET_CONFIG: {arch: mlp, h_size: [64, 64]}
