---
# Define initial hyperparameters
INIT_HP:
    ENV_NAME: IRIS            # Environment name
    UCI_REPO_ID: 53           # Uci repo id  https://archive.ics.uci.edu/
    ALGO: NeuralUCB           # Algorithm
    # Swap image channels dimension from last to first [H, W, C] -> [C, H, W]
    CHANNELS_LAST: false
    BATCH_SIZE: 64            # Batch size
    LR: 0.001                 # Learning rate
    MAX_STEPS: 10_000         # Max no. steps
    EPISODE_STEPS: 500        # Steps in episode
    TARGET_SCORE: 96.         # Early training stop at avg score of last 100 episodes
    GAMMA: 1.0                # Scaling factor
    LAMBDA: 1.0               # Regularization parameter
    REG: 0.000625             # Loss regularization parameter
    MEMORY_SIZE: 10000        # Max memory buffer size
    LEARN_STEP: 2             # Learning frequency
    TOURN_SIZE: 2             # Tournament size
    ELITISM: true             # Elitism in tournament selection
    POP_SIZE: 4               # Population size
    EVO_STEPS: 500            # Evolution frequency
    EVAL_STEPS: 500           # Evaluation steps
    EVAL_LOOP: 1              # Evaluation episodes
    WANDB: true               # Log with Weights and Biases

MUTATION_PARAMS:
    NO_MUT: 0.4                            # No mutation
    ARCH_MUT: 0.2                          # Architecture mutation
    NEW_LAYER: 0.2                         # New layer mutation
    PARAMS_MUT: 0.2                        # Network parameters mutation
    ACT_MUT: 0.2                           # Activation layer mutation
    RL_HP_MUT: 0.2                         # Learning HP mutation
    # Learning HPs to choose from
    RL_HP_SELECTION: [lr, batch_size, learn_step]
    MUT_SD: 0.1                            # Mutation strength
    RAND_SEED: 42                          # Random seed
    # Define max and min limits for mutating RL hyperparams
    MIN_LR: 0.0000625
    MAX_LR: 0.01
    MIN_BATCH_SIZE: 8
    MAX_BATCH_SIZE: 512
    MIN_LEARN_STEP: 1
    MAX_LEARN_STEP: 10

NET_CONFIG:
    latent_dim: 128

    encoder_config:
        hidden_size: [128]

    head_config:
        hidden_size: [128]
