---
# Define initial hyperparameters
INIT_HP:
    ENV_NAME: IRIS   # Environment name
    ALGO: NeuralUCB        # Algorithm
  # Swap image channels dimension from last to first [H, W, C] -> [C, H, W]
    CHANNELS_LAST: false
    BATCH_SIZE: 64            # Batch size
    LR: 0.0001                # Learning rate
    EPISODES: 100             # Max no. episodes
    TARGET_SCORE: 96.         # Early training stop at avg score of last 100 episodes
    GAMMA: 1.0                # Scaling factor
    LAMBDA: 1.0               # Regularization parameter
    REG: 1.0                  # Loss regularization parameter
    MEMORY_SIZE: 10000        # Max memory buffer size
    LEARN_STEP: 1             # Learning frequency
    TOURN_SIZE: 2             # Tournament size
    ELITISM: true             # Elitism in tournament selection
    POP_SIZE: 4               # Population size
    EVO_EPOCHS: 20            # Evolution frequency
    WANDB: true               # Log with Weights and Biases

MUTATION_PARAMS:
    NO_MUT: 0.4                            # No mutation
    ARCH_MUT: 0.2                          # Architecture mutation
    NEW_LAYER: 0.2                         # New layer mutation
    PARAMS_MUT: 0.2                          # Network parameters mutation
    ACT_MUT: 0.2                           # Activation layer mutation
    RL_HP_MUT: 0.2                         # Learning HP mutation
  # Learning HPs to choose from
    RL_HP_SELECTION: [lr, batch_size, learn_step]
    MUT_SD: 0.1                            # Mutation strength
    RAND_SEED: 42                          # Random seed
    MIN_LR: 0.0000625                      # Define max and min limits for mutating RL hyperparams
    MAX_LR: 0.01
    MIN_BATCH_SIZE: 8
    MAX_BATCH_SIZE: 512

NET_CONFIG:
    arch: mlp
    h_size: [128]
