---
algorithm:
    name: PPO
    batch_size: 1024
    lr: 0.0005
    learn_step: 128_000
    gamma: 0.995
    gae_lambda: 0.95
    action_std_init: 0.6
    clip_coef: 0.2
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 1.0
    target_kl:
    update_epochs: 8
    share_encoders: true

environment:
    name: WalkerWalk
    num_envs: 128

mutation:
    probabilities:
        # no_mut: 1.0
        # arch_mut: 0.0
        # new_layer: 0.0
        # params_mut: 0.0
        # act_mut: 0.0
        # rl_hp_mut: 0.0
        no_mut: 0.4
        arch_mut: 0.2
        new_layer: 0.2
        params_mut: 0.2
        act_mut: 0.0
        rl_hp_mut: 0.2
    rl_hp_selection:
        lr:
            min: 0.00005
            max: 0.005
        batch_size:
            min: 64
            max: 512
        learn_step:
            min: 512
            max: 4096
        ent_coef:
            min: 0.001
            max: 0.1
        update_epochs:
            min: 3
            max: 15
    mutation_sd: 0.1
    rand_seed: 42

network:
    latent_dim: 128
    arch: mlp
    encoder_config:
        hidden_size:
            - 256
            - 256
        activation: ReLU
        min_mlp_nodes: 64
        max_mlp_nodes: 512
        layer_norm: true

    head_config:
        hidden_size:
            - 128
        activation: ReLU
        min_hidden_layers: 1
        max_hidden_layers: 3
        min_mlp_nodes: 64
        max_mlp_nodes: 512
        output_vanish: true
        layer_norm: true

tournament_selection:
    tournament_size: 2
    elitism: true

training:
    max_steps: 120_000_000
    target_score: 9000.0
    # pop_size: 1
    pop_size: 4
    evo_steps: 30_720
    eval_steps: 1000
    eval_loop: 1
