---
algorithm:
    name: GRPO
    batch_size: 16
    group_size: 4
    lr: 0.0003
    beta: 0.0005
    clip_coef: 0.2
    max_grad_norm: 0.1
    update_epochs: 2
    temperature: 0.85
    use_vllm: true
    vllm_config:
        tensor_parallel_size: 1
        gpu_memory_utilization: 0.85
        max_num_seqs: 16
        sleep_mode: true

environment:
    env_type: multiturn
    entrypoint: game:GuessTheNumber-v0-easy
    max_reward: 1.0

training:
    max_steps: 4096
    evo_steps: 4096
    pop_size: 1
    evaluation_interval: 10

network:
    pretrained_model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct
    max_context_length: 2048
    lora_config:
        lora_r: 16
        lora_alpha: 64
        target_modules:
            - q_proj
            - k_proj
            - v_proj
            - o_proj
        lora_dropout: 0.05
        task_type: CAUSAL_LM
