---
name: macOS

on:
    workflow_call:

permissions:
    contents: read

jobs:
    tests:
        runs-on: macos-26
        steps:
            - uses: actions/checkout@v5
            - uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: true
                  python-version: '3.13'
            - name: Install dependencies
              run: |
                  uv sync --locked --all-groups --extra all

            - name: Test with pytest
              run: bash scripts/run-tests.sh cov junit --cov-report=term-missing --durations=0 --durations-min=1.0
            - name: Upload junit
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: junit-macos-3.13
                  path: junit-*.xml
                  if-no-files-found: ignore
